name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-jammy

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openvpn-as:$GITHUB_SHA
      
    - name: Tag the image as the latest one
      run: docker --tag openvpn-as:$GITHUB_SHA openvpn-as:latest
      
    - name: Login to dockerhub
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
      
    - name: Push the actual image
      run: docker push openvpn-as:$GITHUB_SHA
      
    - name: Push latest tag
      run: docker push openvpn-as:latest

    
    
