name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-jammy

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openvpn-as:$(date +%s)
    - name: Tag the image as the latest one
      run docker --tag openvpn-as:$(date +%s) openvpn-as:latest
